//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSONFirebirdWebServiceTest.Definitions {
    
    
    public partial class Index {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new JSONFirebirdWebServiceTest.Definitions.Definitions Master {
            get {
                return ((JSONFirebirdWebServiceTest.Definitions.Definitions)(base.Master));
            }
        }
    }
}
